baseURL: http://localhost:1313/
languageCode: fr-fr
title: OpenGento
theme: hugo-fresh

params:
  hero:
    tagline: OpenGento
    subTagline: OpenGento est une association Française loi 1901 dont l'objet est l'organisation d'événements Magento pour la communauté de développeurs.
    buttonText: En savoir plus
    image: illustrations/worker.svg
    bottomIcons:
    - partners/Blackbird-150x45.jpg
    - partners/MonsieurBiz-150x75.jpg
    - partners/logo-occitech-150x39.jpg
    - partners/PH2M-150x44.jpg
  navbar:
    buttonText: Adhérez
    logo:
      src: logos/opengento-150x150.png
      alt: OpenGento logo
    links:
    - text: Evenements
      url: /
    - text: L’association OpenGento
      url: /
    - text: Annuaire
  features:
    tagline: Prochains événements
    subTagline: Lorem ipsum sit dolor amet is a dummy text used by typography industry
    panels:
    - title: Week-end Allègre 2018
      image: illustrations/icons/mouse-globe.svg
      text: This is some explanatory text that is on two rows
      button:
        text: En savoir plus
        url: /
      delay: 1
    - title: Week-end Toulouse 2017
      image: illustrations/icons/laptop-cloud.svg
      text: This is some explanatory text that is on two rows
      button:
        text: En savoir plus
        url: /
      delay: 2
    - title: Organisez votre événement
      image: illustrations/icons/plug-cloud.svg
      text: This is some explanatory text that is on two rows
      button:
        text: En savoir plus
        url: /
      delay: 3
  contact:
    tagline: Drop us a line or two!
  footer:
    image: opengento-150x150.png
    columns:
    - title: Product
      links:
      - name: Discover features
        url: "#"
      - name: Why choose our Product?
        url: "#"
      - name: Compare features
        url: "#"
    - title: Docs
      links:
      - name: Get Started
        url: "#"
      - name: User guides
        url: "#"
      - name: Admin guide
        url: "#"
    followUs:
    - icon: github
      url: "https://github.com/opengento"
    - icon: twitter
      url: "https://twitter.com/opengento"

